repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 21.5b2
    hooks:
      - id: black
        language_version: python3.8

  - repo: https://github.com/prettier/prettier
    rev: 2.3.0
    hooks:
      - id: prettier
        exclude: '^docs/'

  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.27.0
    hooks:
      - id: eslint
        additional_dependencies: ['eslint@7.27.0']

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
      - id: bandit

  - repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
        additional_dependencies: ['types-requests', 'types-setuptools']

  - repo: https://github.com/git-lfs/git-lfs
    rev: v2.13.3
    hooks:
      - id: git-lfs

# Add more hooks here as needed