
version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  build:
    docker:
      - image: cimg/node:16.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build
          command: npm run build
      - run:
          name: Test
          command: npm test

  deploy:
    docker:
      - image: cimg/node:16.0
    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            # Commands to deploy the application
            # This might include pushing to Docker Hub and deploying to a server

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
